version: "3.8"

services:
  spark:
    image: docker.io/bitnami/spark:3.5
    build:
      context: ../
      dockerfile: docker/dockerfile.spark
    env_file:
      - ../.env
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ../data/events:/opt/spark/data/events:ro
      - ../src/data_generator.py:/opt/spark/app/data_generator.py:ro
      - ../src/spark_streaming_to_postgres.py:/opt/spark/app/spark_streaming_to_postgres.py:ro
      - ../jars/postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar:ro
      - ./logs:/opt/spark/logs
    networks:
      - datapipeline
    command: >
      bash -c "sleep 10 &&
      /opt/bitnami/spark/bin/spark-submit 
      --jars /opt/spark/jars/postgresql-42.7.5.jar 
      /opt/spark/app/spark_streaming_to_postgres.py"

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    build:
      context: ../
      dockerfile: docker/dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark


    depends_on:
      - spark
    networks:
      - datapipeline

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ../db/pgdata:/var/lib/postgresql/data
      - ../db/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    networks:
      - datapipeline

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - datapipeline

  generator:
    build:
      context: ../
      dockerfile: docker/dockerfile.generator
    volumes:
      - ../data/events:/opt/generator/data/events
      - ../logs:/opt/generator/logs
    depends_on:
      - spark
    networks:
      - datapipeline

networks:
  datapipeline:

volumes:
  pgadmin_data:
